### ISSUE TITLE
Bitbucket support on KIE Sandbox

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#10]
- Allow users to import individual files from Bitbucket like we do with GitHub
- Allow users to create repositories on Bitbucket like we do with GitHub
- Allow users to import private repositories from Bitbucket, like we do with GitHub
- Allow KIE Sandbox to configure with private instances of Bitbucket, not only bitbucket.com
   - This required creating a new AuthProvider type "bitbucket" and configuring its UI on the Accounts modal
- There might be more to do that are not listed on this issue. Part of the execution of this task is to point those things out, so decisions can be made on how things are going to look like. For example: If you started a new Workspace on KIE Sandbox, what's the UX of creating a repository going to look like? Specially if you have authenticated accounts for both GitHub and Bitbucket.

**Comment by jstastny-cz** [comment]
I will mention also other options below, the final scope will be defined later.

**Comment by jstastny-cz** [comment]
Bitbucket and Gist-like feature? [Bitbucket Snippets](https://support.atlassian.com/bitbucket-cloud/docs/snippets-overview/) 
* API? https://bitbucket.org/blog/snippets-api-wiki-edits-restrictions-and-more

**Comment by jstastny-cz** [comment]
Bitbucket API Docs
* https://developer.atlassian.com/cloud/bitbucket/rest/intro/

Bitbucket NPM package
* https://www.npmjs.com/package/bitbucket
  * Not from atlassian directly, they attempted to fork it (https://www.npmjs.com/package/@atlassian/bitbucket-server), but their package seems to be abandoned.
  * SOLVED: Using direct invocation of REST API using node-fetch.

**Comment by jstastny-cz** [comment]
Investigating an issue with Bitbucket repo creation:
1. mainbranch = main does not work, creates master all the time
2. can't push or clone the repo unless done previously through git manually. Investigating what differences are in play.

SOLVED:
Both worked around by an initial push against target branch (`main` or whatever), that branch is then the only one present (because fresh new repo) and this also resolves problem 2 - consecutive pushes and pulls work correctly.

**Comment by jstastny-cz** [comment]
Known limitation:
* mainbranch definition is not reflected neither in create or update commands: 
  * https://jira.atlassian.com/browse/BCLOUD-20340
  * defaults to master
  * SOLVED: The branch does not exist initially, so first push can be against `main` and that will be the only branch present in the repo afterwards.

**Comment by jstastny-cz** [comment]
For the record, initial support focuses on Bitbucket Cloud REST API v2: https://developer.atlassian.com/cloud/bitbucket/rest/intro/ . Thus supporting bitbucket.org.

The REST API is completely different for Bitbucket Server and Bitbucket Data Center.

**Comment by jstastny-cz** [comment]
Further improvements could be:
- introduce a notion of permissions/privileges that are defined by the oauth token being used - this would make sure control buttons, etc are displaying based on the actual oauth scopes defined by the token.
  - should be available in GitHub response by default
  - bitbucket does not expose the scopes as the x-oath-scopes header is CORS protected, which differs from what GitHub does and might be an implementation mistake on bitbucket side: https://community.atlassian.com/t5/Bitbucket-questions/REST-API-OAuth-Scopes-response-headers/qaq-p/2238751 
- In workspace breadcrumbs - the first entry is an AuthProvider.type which is currently selected for the workspace, which leads to issues: When I have a Gist workspace, and out of that Gist want to create Bitbucket repository, I go, change the auth provider to Bitbucket in Share dropdown -> then the breadcrumb already switches to show Bitbucket authProvider, while it still should probably show rather the workspace.kind-related value - it's still a Gist, until I actually click the `Create Bitbucket repository` button.
- Implement more user-friendly integration for both GitHub and Bitbucket using short-lived access/refresh tokens - this would require dynamic auth of the user(redirect to vendor's auth endpoint) rather than using long-lived App tokens/passwords.

**Comment by tiagobento** [comment]
@jstastny-cz Good points. As for token granularity, I think when moving to OAuth, we won't have much room to let the user select what they want to use.. let's see.

I'm not sure I understand the breadcrumbs thing.. maybe a little video/gif would help?

As for short-lived tokens, definitely we have to look into that :D

**Comment by jstastny-cz** [comment]
@tiagobento ad breadcrumbs - is best visible when user has a Bitbucket Snippet workspace, thus the breadcrumb is showing Bitbucket logo. Let's say user wants to create GitHub repository from this Snippet, so they go, pick GitHub auth in Share dropdown and immediately the icon changes also in the Breadcrumbs above the editor (WorkspaceLabel is the component I think). So before they actually click Create GitHub repository the logo is out of sync (because it reflects selected auth provider, not the actual workspace kind).

![image](https://user-images.githubusercontent.com/11939909/213730899-c927c3d9-dcd5-488f-abbc-c2ad36ccb7ff.png)

You can see here - first is the auth provider currently selected, second is workspace kind ... it's a bit puzzling to me, but I admit, that it might not be actually intended do be hierarchical breadcrumb in a sense `github > repo/gist > path` ... but rather two discrete values standing next to each other.

**Comment by tiagobento** [comment]
Yeah, this header evolved "organically" overtime :) Those are not meant to be read in a hierarchical way, although there's nothing preventing people from doing that :D 

If I understood correctly, the WorkspaceLabel is correctly looking at the WorkspaceDescriptor to draw the logo, right? The moment when the informations are "out of sync" is exactly as you showed on the screenshot. GitHub Auth selected for a Bitbucket Snippet, right? 

TBH I think this is working as expected. In fact, selecting a GitHub auth should only be possible if you expand the options on the AuthSession dropdown, so pretty uncommon, and I assume users then "know what they're doing"? IDK, maybe that's on us :) 

Another thing: It shouldn't be necessary to select the AuthSession prior to creating the repository. In fact, the "Create repository modal" should let you select an AuthSession that's not used by the Workspace yet. The Workspace should incorporate the AuthSession only if the user proceeds with creating the repo.

Does all that make sense?
