### ISSUE TITLE
Copy `kogito-serverless-operator` to `kie-tools`

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#1034]
Create a new package `packages/sonataflow-operator` on `kie-tools`, hosting the relevant parts of https://github.com/apache/incubator-kie-kogito-serverless-operator so that `kn-plugin-workflow` can depend on it, instead of pointing to https://github.com/kiegroup/kogito-serverless-operator.

This task is only to move it and integrate it with the build, no changes to `packages/kn-plugin-workflow` need to be done as part of this task.

**Comment by tiagobento** [comment]
@ricardozanini Hi! I was discussing this task with @thiagoelg, as he is already working on it, and we were able to understand the overall architecture and the pieces that compose the operator and what a release of it means.

Our understanding is that the manager binary needs to be built and the operator image will include it. The `operator.yaml` file is actually how people install the operator, and this `operator.yaml` file has references to the images that are published to Quay.io. All `kogito-swf-builder`, `kogito-swf-devmode` and `kogito-serverless-operator` images. Let us know if we understood something wrong.

Since for Apache KIE 10 we're temporarily copying the operator to `kie-tools`, it occurred to me that the description of this task might be wrong, and we'll actually need to do the release from the copy of the operator that is going to be inside `kie-tools`. To make this happen, the entire `kogito-serverless-operator` needs to be brought in into `packages/kogito-serverless-operator`, so that every part of the build can be done using the other resources that are also part of `kie-tools`, like the images.

So, assuming we understood everything correctly, and assuming that we indeed need to release from `kie-tools`, we'll need to also copy some of the release jobs we have. There are some checks that can be easily ported to `kie-tools`, but the Jenkins release jobs were a bit confusing for us.

@rodrigonull or @jstastny-cz do you think you may be able to help?

Overall, after what we saw, we're ~80% confident that we can integrate this repo inside the `kie-tools` build without problems. The only hard part would be making the E2E tests comply with the conventions we have on `kie-tools`, but this can be addressed with temporary dedicated GitHub Actions workflows like `e2e.yml` and `check-container-builder.yml`

@ricardozanini The `check.yml` job we actually wouldn't need to port, as we integrate the "codegen" part on the build itself, and the CI of `kie-tools` will check for modified files after the build.

@ricardozanini Another thing that would be great for us to understand, because it has to do with how `kie-tools` handles versions, is how do we specify the version of the images that the operator depends on?

Thanks for the help so far!

**Comment by ricardozanini** [comment]
@tiagobento overall, you understood correctly. But don't mind releasing the operator since this is a manual method that we rely on OperatorHub repositories. So after the 10.x images are released, I'll send two PRs to the OperatorHub releasing the Apache SonataFlow Operator there. I just need the images to be pushed to quay/kie-group.

Regarding the images, you can set the naming/version in this file here: https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/version/version.go#L28. We have this script to update it: https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/hack/bump-version.sh

Also, this file can be changed with the images tag too: https://github.com/apache/incubator-kie-kogito-serverless-operator/blob/main/config/manager/controllers_cfg.yaml#L11-L26

**Comment by tiagobento** [comment]
@ricardozanini Ok, thanks! 

I understand that running `hack/bump-version.sh` will also update references to images like `kiegroup/kogito-swf-builder-nightly:latest`.

**Comment by tiagobento** [comment]
@ricardozanini The `quay.io/kiegroup/kogito-serverless-operator` needs to be published, right? We can do it on the `kie-tools` Jenkins jobs like we're doing for `kogito-swf-{devmonde,builder}. cc @rodrigonull 

@ricardozanini This is the only image that `kogito-serverless-operator` builds, or are there more?

**Comment by ricardozanini** [comment]
@tiagobento only this image is required for release.

After publishing the images, I can do the release in the OperatorHubs repos. We can't automate this task because of the policy restrictions of OperatorHub. It must be the operator's maintainer to open the PR.

Unless we use my PAT token in the CI, which is, of course, a security flaw and I'm not keen to do it.

**Comment by tiagobento** [comment]
Ok, so we'll need a new release job to publish the operator image to `quay.io/kiegroup` too. Thanks for the confirmation.

cc @rodrigonull

**Comment by tiagobento** [comment]
Created 
- https://github.com/apache/incubator-kie-issues/issues/1121
