### ISSUE TITLE
Upgrade `node` from `16` to LTS (`18`) on `kie-tools`

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#105]
`kie-tools` is using a quite old node version (`16`). It would be good to update it to the latest stable version (`18`) so it doesn't  stay behind too much.

See https://github.com/nodejs/release#release-schedule

**Comment by tiagobento** [comment]
To keep as a reference when we're moving from 18 to 20, we forgot some places:

- `pkg` builds targeting `node16` for `image-env-to-json` and `form-generation-tool`
- `packages/git-cors-proxy-image/Containerfile` base image is `registry.access.redhat.com/ubi9/nodejs-16-minimal`
  - Also, we need to provide a fixed version for this base image, since right now the build is time-dependent, downloading `latest` on each build.
