### ISSUE TITLE
Improve Import Resolver error messages to be more user friendly

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1150]
The `ImportDMNResolverUtil` class holds the logic that resolves a DMN import.

If that logic is not able to resolve the DMN assets to be imported, the current error messages are misleading and don't help the final help to understand.
This ticket's goal is to provide better messages to the final users, together with a DEBUG logs message to better investigate the code in case of issues.

In addition, we found several issues in the logic that will be addressed in a separate ticket: https://github.com/apache/incubator-kie-issues/issues/1383

**Comment by gitgabrio** [comment]
Thanks @yesamer !
TBH, I'm still a little bit confused about that namespace thing.
My understanding (reading specs) is that:
1. it defines the "domain" of all definitions of a given model
2. there should be no collision when importing models


From the above, I see only two kind of contexts defined: stand-alone dmn and dmn with import. 
But there is a third case, i.e. multiple models, some related and some not, in the same _project_. In that case, what's the meaning of "globally unique" ? Depending on the interpretation, a given _project_ could be invalid at all, or not, and consequently the code should behave one way or the other.
If multiple dmn with the same namespace are allowed in the same _project_, then the `locationURI` should be mandatory, because there would be no other way to differentiate them. 
But since it is not, it seems that namespace alone should be enough to correctly identify a model inside a _project_, and that means namespace should be unique inside a given _project_.

@baldimir ^^
