### ISSUE TITLE
Performing the `undo` operation after resetting the expressions crashes the new DMN Editor

### ISSUE THREAD

**Issue by ljmotta** [apache/incubator-kie-issues#1182]
Performing a `undo` operation after reseting an expression crashs the editor. It's necessary to investigate the root cause, and the reproducer. 

File:
https://gist.github.com/ljmotta/144abe93b458247414cc4e84d0e78d0a

Video:
https://github.com/apache/incubator-kie-issues/assets/24302289/d251dce0-df0a-421a-acdd-4e17a1c6befe

**Comment by danielzhe** [comment]
It looks like we have two issues: the one you reported, which I'm able to get a stable reproducer and a new one. The new one gives us the error ""message": "A node Icon must exist for all types of node""

I think I found the root of the one you reported, but I need to investigate a bit more to find the root of the second one.

**To reproduce the error you reported, the steps are the following:**
1. Open a Context or any iterator expressions (`for`, `every`, `some`, and probably `filter`). **The error does not happen with function and in Context Expressions it only happens in the result**
2. Set a nested expression something like a Decision Table
3. Type something in the Decision Table
4. Reset
5. Add a Literal Expression
6. Type something
7. Undo

The issue is that idRandomizer [here](https://github.com/apache/incubator-kie-tools/blob/c3fabfe3a0914e6d43fc17068027298518249769/packages/xml-parser-ts/src/idRandomizer.ts#L128 ) is trying to set a property called `@_id` in a readonly object. 

This is caused because when we reset the expression in `for`, `every`, `some`, and `context`, we set its nested expressions as an empty child with only `expression` as `undefined`. In `Function` we don't do that: we preserve the `@_id`.

Notice in `context` as we handle different reset result and reset entry, [here](https://github.com/apache/incubator-kie-tools/blob/c3fabfe3a0914e6d43fc17068027298518249769/packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx#L378).

I'm not sure yet why this is happening only when undo/redo. I got the same error with "redo" too. Still investigating.,
