### ISSUE TITLE
BPMN/DMN : When Zooming in/out the floating toolbox changes its size

### ISSUE THREAD

**Issue by inodeman** [apache/incubator-kie-issues#121]
When zooming in and out the toolbox changes size when it should stay the same size. The user should expect a standard size of the toolbox. See image

Zooming in
<img width="603" alt="image" src="https://user-images.githubusercontent.com/39567766/220198184-c73a4246-c8d1-4f6c-aa02-e22bd76fd2bc.png">

Zooming out

<img width="376" alt="image" src="https://user-images.githubusercontent.com/39567766/220198241-acf5dae1-9742-478e-9d99-126a8e306110.png">

**Comment by tiagobento** [comment]
I know this issue was reported for both BPMN and DMN Editors, but as part of #439, I found out it's really not a great UX if the Node toolbars stay at the same size when the Diagram itself is zoomed in/out. Reactflow allows this very easily with Node toolbars (https://reactflow.dev/docs/api/nodes/node-toolbar/), but I actually preferred the behavior that this issue described... Can you share more thoughts about this @inodeman ?
