### ISSUE TITLE
The for loop wrongly behaves when there are nested arrays in the  iteration contexts

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1350]
The following FEEL expression:

`for x in [ [1,2], [3,4] ], y in x return y`

should return `[1, 2, 3, 4]` 

but it currently returns `[1, 2, 1, 2]`

**Comment by yesamer** [comment]
Most likely related to https://github.com/apache/incubator-kie-issues/issues/774

**Comment by yesamer** [comment]
//cc @bncriju

**Comment by gitgabrio** [comment]
@yesamer 
I've found the point where it fails, but it is int the core logic itself, where during the loop evaluation, only the first element is stored (and retrieved ) as `x` variable (so, the `[1, 2]` in the given example):


I'm trying also another example
`for x in [ 1, 2, 3, 4 ], y in x return y` 
that, apparently, should return `[1, 2, 3, 4]`
but it also returns `[1, 1, 1, 1]`  (since `1` is the first `x` element)

**Comment by gitgabrio** [comment]
@yesamer @baldimir 
Reading spec:

> An iteration context may either be an expression that returns a list of elements, or two expressions that return
integers connected by “..”. Examples of valid iteration contexts are:
• [ 1, 2, 3]
• a list
• 1..10
• 50..40
• x..x+10
• @”2021-01-01”..@”2022-01-01”

and

> for i in [i1,i2], j in [j1j2] return e = [ r1, r2, r3, r4 ]

it seems that this expression is wrong
`for x in [ 1, 2, 3, 4 ], y in x return y` (x is always a number)

but this should work

`for x in [ [1,2], [3,4] ], y in x return y` (x is alway a list)

Unfortunately, it seems that our implementation is expecting only statically defined lists.

I'm digging further...
