### ISSUE TITLE
`matches()` function wrongly behaves - checks and unicode

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1409]
TCK Tests revealed some cases where `matches()` wrongly behaves.

1.  `matches("abracadabra", "bra", "p")` should return an error, as the "p" flag doesn't exist; (Please check all the functions where the flags parameter is used e.g. `replace()`)
2. `matches("\u212A", "k", "i")` should return true. \u212A is the [Kelvin Sign](https://codepoints.net/U+212A?lang=en), basically a K. Before fixing that, double-check in the specs that this is the expected behavior 
3. `matches("input", "pattern", " ")` same as point 1.
4. `matches("input", "pattern", "X")` same as point 1.
5.  `matches("hello world", "hello\ sworld", "x")`The `x` is not supported. (Please check all the functions where the flags parameter is used e.g. `replace()`)
6. `matches("h", "(.)\3")` `matches("h", "(.)\2")` and `matches("input", "\3")` should fail. Please investigate why they should fail

**Comment by gitgabrio** [comment]
@yesamer @bncriju @baldimir 

For the "kelvin sign", the required flags are `iU`

`matches("\u212A", "k", "i")` -> `matches("\u212A", "k", "iU")`

Here, the problem is to fix the test (= add the `U` flag) or enable the `U` flag by default in our code.
Reading  "String functions" examples and string definition on DMN spec, it seems we have to enable "unicode" by default

![image](https://github.com/user-attachments/assets/b4190655-777e-4654-a8b5-59191f57e1d3)

**Comment by yesamer** [comment]
I run your changes against the TCK tests, and cases 5. and 6. are still not working. Is that intended?
