### ISSUE TITLE
It's not possible to refer to an external nodes in `informationRequirement` and `knowledgeRequirement`

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#1411]
Using `informationRequirement` and `knowledgeRequirement` can refer to internal and external nodes using the `href` attribute.
Please notice the case of internal nodes above:

```
        <informationRequirement>
            <requiredDecision href="_decision_001"/>
        </informationRequirement>
        <informationRequirement>
            <requiredInput href="_input_001"/>
        </informationRequirement>
        <knowledgeRequirement>
            <requiredKnowledge href="_bkm_001"/>
        </knowledgeRequirement>
```

This case is currently working as expected.

The spec `12.3.2 References within the DMN XSD` states that is it possible to refer to external nodes using the following syntax:

```
        <informationRequirement>
            <requiredDecision href="http://www.montera.com.au/spec/DMN/0091-local-hrefs#_decision_001"/>
        </informationRequirement>
        <informationRequirement>
            <requiredInput href="http://www.montera.com.au/spec/DMN/0091-local-hrefs#_input_001"/>
        </informationRequirement>
        <knowledgeRequirement>
            <requiredKnowledge href="http://www.montera.com.au/spec/DMN/0091-local-hrefs#_bkm_001"/>
        </knowledgeRequirement>
```

This case is currently NOT working

**Comment by gitgabrio** [comment]
@yesamer 
IIUC, [this](https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0091-local-hrefs/0091-local-hrefs.dmn) is the test/model you are referring to, but the  `namespace` in the href attribute
`href="http://www.montera.com.au/spec/DMN/0091-local-hrefs#_decision_001"` 
is the namespace of the model itself

`<definitions namespace="http://www.montera.com.au/spec/DMN/0091-local-hrefs"`
so it is not a reference to an external node
(pls notice there are some tests/examples using such elements from external nodes, e.g. [this](https://github.com/apache/incubator-kie-drools/blob/5456bc313516fa7cfa8f1042a332480a3aaae5d5/kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/imports/ImportsTest.java#L163))

**Comment by yesamer** [comment]
@gitgabrio Yes, that particular case refers to the same document. BUT, according to the specs ^^ (12.3.2 References within the DMN XSD) it should work with external nodes too. Is it correct or did I misunderstand the specs?

**Comment by yesamer** [comment]
@gitgabrio So that means it's not working in the case the namespace points to itself, is that right?

**Comment by gitgabrio** [comment]
@yesamer 
When the engine find that syntax
`http://www.montera.com.au/spec/DMN/0091-local-hrefs#_decision_001` 
it tries to resolve the node looking in the imports with the `http://www.montera.com.au/spec/DMN/0091-local-hrefs` namespace.
But since there are not such imports, it fails.

`Yes, that particular case refers to the same document. BUT, according to the specs ^^ (12.3.2 References within the DMN XSD) it should work with external nodes too. Is it correct or did I misunderstand the specs?` 
yup, and it actually works with real external nodes (e.g. [this](https://github.com/apache/incubator-kie-drools/blob/5456bc313516fa7cfa8f1042a332480a3aaae5d5/kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/imports/ImportsTest.java#L163))

` So that means it's not working in the case the namespace points to itself, is that right?` 
Yup. IIUC the specs, the test is wrong, because the specs refer to external nodes, and this is not the case.
