### ISSUE TITLE
maven metadata for optaplanner does not contain any versions before 10.0.0

### ISSUE THREAD

**Issue by Remigius2011** [apache/incubator-kie-issues#1681]
see https://repo.maven.apache.org/maven2/org/optaplanner/optaplanner-test/maven-metadata.xml

This breaks our version check, as the current "final" version is 9.44.0.Final which cannot be found in the metadata. There are not even any release notes to be found for 10.0.0, so we cannot assess the risk of upgrading to 10.0.0 at all.

for a correct metadata file, see e.g. https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml

**Comment by yesamer** [comment]
Hi @Remigius2011, we are currently releasing version 10.0.0 and the process will be completed in the next few hours. That means there could be some unexpected issues during the release and missing stuff like changelog and a proper announcement. This is our first release in Apache, so it's expected, at the  end of the process we plan to give you all information
I see your point, but I'm afraid we are not allowed to add any release before 10.0.0 in the Apache repo, simply because all the previous releases were not managed under the Apache management  (e.g. 9.44.0 is the last version released under Red Hat management.)

@porcelli @baldimir @LightGuard correct me if I'm wrong please.

**Comment by Remigius2011** [comment]
@yesamer it's ***not*** about anything in the ***git*** repo, but about the maven repo, which is apache for all publishers of maven artifacts, regardless of their organization. this maven repo already contains all previous releases, but now the maven-metadata is plain wrong, which surely breaks our own version check (and therefore our build), but might break other person's/organization's builds as well. The existing versions can be seen here:

https://mvnrepository.com/artifact/org.optaplanner/optaplanner-core
https://mvnrepository.com/artifact/org.optaplanner/optaplanner-test

or here:

https://repo.maven.apache.org/maven2/org/optaplanner/optaplanner-core/
https://repo.maven.apache.org/maven2/org/optaplanner/optaplanner-test/

As you can easily verify by scrolling to the bottom of the latter links, the metadata contains ***only*** v 10.0.0, which isn't even there, and all the other versions, which ***are*** there are missing. As these versions are in the repo, I think it is reasonable to have them in the metadata as well.

So, please, if you are working on the release process, re-add the past versions - which are available and should remain available - to the maven metadata again.

**Comment by yesamer** [comment]
@Remigius2011 Thank you for your explanation. I'm not in charge of the release process, but I'll notify this issue.

**Comment by yesamer** [comment]
@porcelli Can you please address this issue? Thx you :)

**Comment by brianf** [comment]
Now that 10.0.0 is available in the repo, is there still a real issue with the metadata missing the 9.x versions? This occurred because of the migration to the new repo and only the new release is present, so when the metadata is generated, it isn't aware of the previous versions. Most processes don't use this metadata anyway. So I'm trying to judge is this causing real problems still? It can be fixed, but not easily.

**Comment by porcelli** [comment]
@brianf I'm personally ok with leave as is...

somehow it could be considered a new start... as it has moved to Apache Foundation.

@Remigius2011 ^

**Comment by Remigius2011** [comment]
@porcelli if you consider it as a restart, sou should imo change the group id and restart the metadata from scratch. If the history is missing, you break things that are currently working, as I said, in our case the version check which is an important security measure for us. Here's a link to the description of maven metadata:

https://maven.apache.org/repositories/metadata.html

I cite:

`The artifactId level metadata (found in directory of artifactId) serves purpose of version discovery. This metadata contains list of versions of given GA coordinates. `

Certainly, 10.0.0 is not the "release" version, as it is not even there yet.

Imo, close as completed is plain wrong. If you stick with your opinion that this is ok, please at least be honest and close it with `wont-fix`, because it is not completed at all.

**Comment by porcelli** [comment]
You have a fair point, @Remigius2011 - just updated the status.

**Comment by Remigius2011** [comment]
@porcelli what do you mean by fake point?

**Comment by porcelli** [comment]
I'm so sorry, my phone auto-correct misspelled! you have a *fair* point :)

**Comment by Remigius2011** [comment]
OK, meanwhile I have upgraded to 10.0.0 - no problem, and to Timefold - no problem either. We'll probably implement a setup where we can compare the two.
