### ISSUE TITLE
Support file extensions that are not lower-case on KIE Tools Channels

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#20]
When opening files with supported extensions not written in lower-case, some problems happen in our Channels.

This issue is to test opening `.BPmN` and `.DMN` (etc) files in all our Channels (KIE Sandbox, VS Code, Chrome Extension, Standalone etc) and see if it works. If not, a fix is expected.

**Comment by jomarko** [comment]
Doing checks right now

- [x] KIE Sandbox
- [x] VS Code (DMN, BPMN)
- [x] Chrome extension (DMN, BPMN)

**Comment by jomarko** [comment]
@tiagobento hello, I think we can close this issue.

I can confirm BPMN and DMN files can be opened currently on Sandbox, VS Code and Chrome regardless of the extensions upper/lover case (dMn, BPmn, ....) worked

For PMML files holds true the same as above ^, however just on Sandbox. However I think it is an expected behavior that PMML files are not supported on Chrome and VS Code.
