### ISSUE TITLE
Keyboard shortcuts stop working after blurring out of some components on the BeeTable

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#210]
There are some erratic behavior with keyboard shortcuts in the Boxed Expression Editor.
Case 1:
1. In a Decision Table, open a header popup
2. Do some change
3. Click in a editable cell
4. Try to type something
5. You'll notice that you are unable to edit the cell without clicking on it again

Case 2:
1. Start to edit a cell
2. Click in another cell
3. You'll notice that you are unable to edit the cell without clicking on it again

Video for Case 1 and 2:

https://github.com/kiegroup/kie-issues/assets/7305741/b06dd546-6bfb-489f-864d-8149ba63ec4b

Case 3:
Shortcuts like CTRL + Z, CTRL + Shift + Z or CTRL + S does not work when Boxed Expression Editor is focused

Also it is important to notice that this issue was introduced because of a "FIXME" in the code. If you uncomment the block of code with FIXME, the case 1 and 2 does not happen but another serious issue is introduced causing the selection become very buggy (wrong cells selected, selection spread over editor, cells that does not unselect, and so on) after user delete or add rows. 

```[tasklist]
### Acceptance criteria
- [ ] User should be able to edit a cell when it is selected without having to select it again
- [ ] Shortcuts should work (see https://github.com/kiegroup/kie-issues/issues/214 which is related to this one) despite the focus
- [ ] Selection of cells should properly work when deleting or adding rows/columns
```

**Comment by danielzhe** [comment]
The shortcut keys (like CTRL + Z or Command-Z in Mac) stop working only when the BeeTable is focused.

It starts to work again if the focus in BEE table is lost like when you click in the Properties Panel or in the blank area in the screen (the empty area between the Table in BEE and the Properties panel, for example).

I think this is happens because the "React world" is handling the shortcuts and not letting them to"bubble" to the "GWT world" that handles Undo, Redo, Save, and so on. So when the React component (the BEE table) lost its focus, it does not handle it anymore and it can bubble freely to the GWT world.
