### ISSUE TITLE
DMN Runner table output column width is lost once DMN Runner table inputs are changed

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#266]
During reporting #265, another issues was spotted that is related also to DMN Runner table. The problem is in resizing output columns. Output columns width is reset with each input columns value change.

### Steps to reproduce
1. Start with steps from #265
2. Fill in DMN inputs with some data and resize the 'Habitability' output column, like [1]
3. Then change some input column value, the output column width change will be lost [2]

[1]
![Screenshot 2023-05-17 142448](https://github.com/kiegroup/kie-issues/assets/8044780/93a4b15a-bd1c-4ead-8802-346c61fbdfea)

[2]
![Screenshot 2023-05-17 142823](https://github.com/kiegroup/kie-issues/assets/8044780/29743844-7898-46da-91eb-d754819ce05b)

_Originally posted by @jomarko in https://github.com/kiegroup/kie-issues/issues/265#issuecomment-1551304265_

**Comment by ljmotta** [comment]
This is happening because we don't persist the width of the output column. On every change the output table is re-rendered, causing the reset.
We have an issue to implement the column width persistence: https://github.com/kiegroup/kie-issues/issues/229

I guess we could move the desired behavior covered in this issue to the #229 , WDYT?

**Comment by jomarko** [comment]
Closing in favor of #229

Thank you for a link @ljmotta
