### ISSUE TITLE
KIE Sandbox shows a blank page in Firefox

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#337]
If you try to open the last version of KieSandox in Firefox, an empty page is shown. --> https://sandbox.kie.org/dev/#/

<img width="1530" alt="Screenshot 2023-06-13 at 12 02 07" src="https://github.com/kiegroup/kie-issues/assets/16005046/219a81a6-8e3c-4bab-8050-594ac86d657b">

The root cause is an NPE

```
Uncaught TypeError: env is undefined
    Component IncompatibleBrowser.tsx:52
```

**Comment by yesamer** [comment]
@tiagobento Code seems correct to me, is probably the root cause related to `env = useEnv()` still not being initialized at that time? Any hint?

**Comment by jomarko** [comment]
Hi @tiagobento @yesamer , I was interested, if this issue is still reproducible and did some manual tests. Here are my findings.

# Issue Still Exists
Once user tries to open **sandbox.kie.org** in **Firefox**, there is still the same error in the logs:
```
Uncaught (in promise) TypeError: env is undefined
```

It is a very strange, because it is related to code of the function component `IncompatibleBrowser.Component`:
```
const { env } = useEnv();
```

And similar short snippet is used in our codebase many times, for example in the `AboutButton` and that button works properly once I run **sandbox** on the **Firefox** see next section.

# Firefox seems compatible
Currently for **online-editor** we do not list **Firefox** as compatible browser. However comparing:
- **online-editor** compatibility [mechanism](https://github.com/apache/incubator-kie-tools/blob/main/packages/online-editor/src/workspace/startupBlockers/IncompatibleBrowser.tsx) 
- with **serverless** compatibility [mechanism ](https://github.com/apache/incubator-kie-tools/blob/main/packages/serverless-logic-web-tools/src/workspace/startupBlockers/SupportedBrowsers.ts)


I decided to try **Firefox**

So changed **online-editor** `isCompatibleBrowser` constant to:
```
const isCompatibleBrowser = Bowser.getParser(window.navigator.userAgent).satisfies({
  chrome: ">4",
  edge: ">=79",
  firefox: ">=38",
  safari: ">=16",
  mobile: {
    safari: ">=16",
  },
});
```

Then everything seems to be working:
- creating assets
-  importing assets/folders
- integrating sandbox with github account
- DMN Runner and Extended Services

![Screenshot 2024-01-30 130721](https://github.com/apache/incubator-kie-issues/assets/8044780/3c990c92-23ad-414c-9431-a3c443678e98)


# Solution
I tend to think we could mark **Firefox** as compatible for **online-editor** because after my manual test it seems to me as working. Or is there some reason to keep it incompatible? Maybe there is reason, I came to the project later, so asking, if there is reason, I am fine to keep it uncompatible.

However that still doesn't answer, why the `useEnv()` snippet causes error. I am not sure how to start "searching solution" for this effectively. General React documentation for custom hooks doesn't touch similar specic situations.

**Comment by yesamer** [comment]
@jomarko Thank you for your brilliant analysis. I did some tests 1 year ago, and I came to the same results and conclusion. After a discussion with @tiagobento, I understood that the GWT layer works "by change", as the GWT layer is not effectively compilated to support Firefox. For that reason, we agreed to not support Firefox until we remove the GWT layer at all.
I'm quite sure nothing changed in the meantime, so I guess that decision is still valid.

**Comment by yesamer** [comment]
About the possible solution, since 6-7 months ago, the following screen appeared when opening KIE Sandbox in Firefox:

![image](https://github.com/kiegroup/kie-tools/assets/32301411/440788e9-b960-4022-8597-193533435900)

I would just restore that panel and put Firefox in the supported browsers list just after we removed the GWT layer

**Comment by jomarko** [comment]
So for later reference, we need to wait until https://github.com/apache/incubator-kie-issues/issues/445 is done. And the same happens with Bpmn and SceSim?

**Comment by yesamer** [comment]
@jomarko Precisely. Until that moment, the scope of this ticket is to restore the above screen, investigating why ` env = useEnv()` doesn't work
