### ISSUE TITLE
CDN URL to latest Standalone Editors does not point to latest DMN Editor

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#358]
The same will be probably true also for BPMN/Workflow.

### Steps to reproduce
- In kie sandbox, click 'embed' option in 'share' menu [1]
- Copy the 'iframe' code [2]
- put it into a html file like [3], please rename 'embed.txt' to 'embed.html' once downloaded on your machine
- open [3] with browser
- if you check documentation tab [4], you will notice the content design is older than latest 'documentation' tab in kie sandbox [5]

[1]
![Screenshot 2023-06-21 085515](https://github.com/kiegroup/kie-issues/assets/8044780/28a298bd-4403-4f3c-8a24-1213914ae0ba)

[2]
![Screenshot 2023-06-21 085527](https://github.com/kiegroup/kie-issues/assets/8044780/2da2645d-dc4b-471e-9c03-97e9cbe22a04)

[3]
[embed.txt](https://github.com/kiegroup/kie-issues/files/11814452/embed.txt)

[4]
![Screenshot 2023-06-21 085942](https://github.com/kiegroup/kie-issues/assets/8044780/f6cfa0bf-b686-4fd6-8811-0426055b277c)

[5]
![Screenshot 2023-06-21 090057](https://github.com/kiegroup/kie-issues/assets/8044780/708008ea-a73b-47ea-9a68-c24b652072f0)

**Comment by tiagobento** [comment]
Good catch. Looks like this URL is not being updated as part of the release scripts. It's pointing to version 0.11.0 =D 

See https://github.com/kiegroup/kogito-online/tree/gh-pages/standalone/dmn

**Comment by yesamer** [comment]
@tiagobento Do we have a reliable source to retrieve the kie-tools-version at runtime, in order to compose the correct symlink? 
`https://kiegroup.github.io/kogito-online/standalone/dmn/%BUILD%/index.js`

In the "About" modal, I found the version 
<img width="509" alt="Screenshot 2023-09-08 at 17 50 35" src="https://github.com/kiegroup/kie-issues/assets/16005046/753d614b-6374-4110-9d0c-9173966e92d0">
that relies on this value: `process.env.WEBPACK_REPLACE__buildInfo;`

But I think that is not the correct choice, as in some environment (local, and product version I guess?) the build info is:
<img width="509" alt="Screenshot 2023-09-08 at 17 50 35" src="https://github.com/kiegroup/kie-issues/assets/16005046/11818262-2182-4495-b7d8-3f0cfb30f491">

I guess we need a specific variable to manage the standalone editors: eg. **LAST_STANDALONE_EDITORS_VERSION**
