### ISSUE TITLE
Fix @kogito-apps/process-form: doesn't display custom forms.

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#526]
Although the **form-generation-tool** generates the process forms, the **process-form** component still uses the default autogenerated form... we should make it use the custom if provided by the app.

Steps to reproduce:
1. Generate **patternfly** forms using *form-generation-tool* for any BPM Quarkus project in kogito-examples (for example [process-usertasks-quarkus-with-console](https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-usertasks-quarkus-with-console))
2. In the project `pom.xml` add a dependency to the `runtime-tools-quarkus-extension`
3. Start the Kogito project in dev mode (`mvn clean quarkus:dev`)
4. Open the Dev ui (`http://locahost:8080/q/dev`) and click on the *Process Instances* link inside the *Runtime Tools Quarkus Extension* and start a new process instance, de default form will be displayed instead of the one generated by the *form-generation-tool*

**Comment by jomarko** [comment]
Will be addressed via https://github.com/apache/incubator-kie-kogito-apps/pull/1927

**Comment by Abhitocode** [comment]
Hi @eduardocerqueira, worked on the **process-usertasks** example with in **bamoe-9.1.0rc2-examples**. Updated the necessary settings and dependencies but due to missing docker image yet be published, not able to compile. Tried different alternatives but error remains the same. Hopefully will find a solution soon.


![Image](https://github.com/apache/incubator-kie-issues/assets/164050036/3739ceca-2335-4cf3-9136-d703b7b3a2e6)
