### ISSUE TITLE
standalone-editors doesn't load the new Boxed Expression Editor

### ISSUE THREAD

**Issue by yesamer** [apache/incubator-kie-issues#575]
After the merge of ticket #358, CDN URL now points to the latest produced JS file (0.31.0).
That update, reveals that the produced JS file doesn't contain all the required `css`, `js` and `woff` resources to correctly work.

To reproduce the issue, just follow the same steps described in #358 and open the browser inspector.

<img width="1526" alt="Screenshot 2023-09-18 at 12 16 19" src="https://github.com/kiegroup/kie-issues/assets/16005046/30d61153-ca52-4247-9565-1b27b619965f">

As a consequence of this issue, the new Boxed Expression is not correctly loaded.

**Comment by tiagobento** [comment]
@yesamer Static assets are bundled in the `index.js` file. This was made because we couldn't override GWT's static asset loader. Instead, we let them error out and include them prior to rendering the editors.. See:
- https://github.com/kiegroup/kie-tools/blob/main/packages/kie-editors-standalone/src/dmn/DmnEditorResources.ts
- https://github.com/kiegroup/kie-tools/blob/main/packages/kie-editors-standalone/src/bpmn/BpmnEditorResources.ts

Closing this issue now, as there's nothing to do..

**Comment by tiagobento** [comment]
Reopening as I missed this part of the description 

> As a consequence of this issue, the new Boxed Expression is not correctly loaded.
