### ISSUE TITLE
Semantics of `hours` is implemented wrong

### ISSUE THREAD

**Issue by hanjoosten** [apache/incubator-kie-issues#583]
# What happend
I have a duration `PT24H`. If the hours are calculated from this, the result is `0`. 

# What I expected
I expect the result to be `24`

# Analisys
The handbook actually suggests that the outcome is correct: https://kiegroup.github.io/dmn-feel-handbook/#days-and-time-duration

However, the DMN spec (paragraph `10.3.2.3.7 days and time duration`) clearly states that the duration should be thought of as a number of seconds. The `hours` function should return the value devided by the number of seconds per hour (rounded?).

**Comment by hanjoosten** [comment]
The [regression tests](https://github.com/apache/incubator-kie-drools/blob/c1bf134ace3373b520887a9d64d2d77c38d16438/kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/FEELDateTimeDurationTest.java#L244) is according to the handbook, hence also wrong

**Comment by yesamer** [comment]
@baldimir ^^

**Comment by baldimir** [comment]
This is not a bug, because in the specification, as defined in the Table 66: Specific semantics of date, time, and duration properties, e.g. hours is defined as 

"The normalized hours component of a days and time duration
value. Since the value is normalized, this property must return an
integer in the interval [0..23]. This property returns null when
invoked on a years and months duration value."

It needs to be within interval of 0..23. Please review and close the issue if you agree it is not a bug.

**Comment by hanjoosten** [comment]
I see. This is interesting. The spec might contradict itself at this point:
![image](https://github.com/kiegroup/kie-issues/assets/1159672/d468cd2f-77bd-47bf-928f-b76326777ef5)

**Comment by hanjoosten** [comment]
Based on description in the contents of Table 66, the meaning of the `hours` function is clearly different than what I expected. So in order to have a function that works according to my expectation, I have to write it myself, which is straightforward. Thanks for the explanation.
