### ISSUE TITLE
`mvn package` throws an exception in Kogito project in Microsoft Windows machines with `quarkus.package.type=uber-jar`

### ISSUE THREAD

**Issue by jaimeizuz** [apache/incubator-kie-issues#717]
Packaging a Kogito project containing .dmn or .bpmn files as an uber-jar throws an exception in Windows-based machines. It doesn't happen when using Linux operating systems.

Steps to reproduce:
1. git clone https://github.com/jaimeizuz/quarkus-dmn-uberjar-example.git (it's just a project generated with code.quarkus.io with Kogito Decisions, RESTEasy Reactive and RESTEasy Jackson, and then the <quarkus.package.type>uber-jar</quarkus.package.type> is added to pom.xml).

2. mvn clean package Error will then happen.

I've attached logs related to a mvn -X clean package in my Windows machine, everything related to my setup (OS, java version, maven version) is in there.
[mvn-package.log](https://github.com/apache/incubator-kie-issues/files/13448870/mvn-package.log)

[Zuilp Discussion](https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Kogito-Quarkus.20application.20failed.20to.20start)

**Comment by yesamer** [comment]
Hi @baldimir @gitgabrio and @mariofusco 

I analyzed this issue based on the above reproducer, log, and zulip discussion.
I put a breakpoint near: `io.quarkus.deployment.pkg.steps.JarResultBuildStep.copyCommonContent (JarResultBuildStep.java:1180)` to determine which kind of Path was passed (most of the time, when an issue occurs in Windows-os only, it's related to the path format management), and here you can see the list in the below image:

<img width="471" alt="Screenshot 2024-02-08 at 09 12 19" src="https://github.com/apache/incubator-kie-issues/assets/16005046/e2537b1d-3221-4bcf-bd87-f29bbcdb8cb9">

The first item is the one that leads to the exception. As you may notice, it's the only item with a OS-dependent (Windows) Path.

The origin of that path string is the `GeneratedFile.java` class in drools repo.
<img width="1063" alt="Screenshot 2024-02-08 at 10 19 25" src="https://github.com/apache/incubator-kie-issues/assets/16005046/058202f0-92cf-4c8b-bc84-9e093a2bed99">

For testing purposes, I forced that `pathAsString` to always hold a POSIX-based path, replacing all the  "\\" with a "/", and that fixes the issue.
I'm aware this can be proposed as the effective solution for this issue, because of its potential impact (that `pathAsString` is used in several places) and I guess we should define a more "structural" solution based on its scope.

**Comment by gitgabrio** [comment]
THanks @yesamer !
Some suggestion/remarks:
1. would be polssible to use the `File.separator`, instead of `replacing all the "\" with a "/",` ?
2. would it be possible to also fix that -> `public static final String META_INF_RESOURCES = "META-INF/resources/";` with same logic ?
3. if you look for `File.separator` in the code, we alredy used that a lot during previous cleanup/refactoring related to same issue

**Comment by yesamer** [comment]
@gitgabrio 

1. I guess that every Path managed in `io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar` must always be in POSIX format, disregarding of the OS, if I'm not wrong.
2. Yes
3. Thanks!
