### ISSUE TITLE
Unhelpful warning: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#72]
This was filed from the community as [this JIRA](https://issues.redhat.com/browse/KOGITO-8343). 

One of my decisions produced a warning, saying:

    Skipped Decision Table Analysis of table 'status BT' because: Index 0 out of bounds for length 0

As a modeller, this doesn't give me any clue about what is going on, let aside what to do about it. I really appreciate any comment at compiletime, but it should be helpful. 

Example DMN files are available in the linked community JIRA. 

Acceptance criteria:
- Reproduce the problem using the linked DMN files. 
- Fix the problem in an appropriate way based on what is causing that. (The unhelpful message may be just a consequence of some other problem, we may not need a new error message for this) 
- New code has 100% code coverage. 
- Automated test that reproduces the problem added to the Drools repository.

**Comment by gitgabrio** [comment]
@tarilabs @baldimir 
I see two different problems raised from this issue

1. The code that origin the warning is actually throwing an exception due to unguarded code:
[Bound<?> lastBound = bounds.get(0);](https://github.com/kiegroup/drools/blob/ca1a166c609cc7b3e2867b7968a92adeff80d630/kie-dmn/kie-dmn-validation/src/main/java/org/kie/dmn/validation/dtanalysis/DMNDTAnalyser.java#L467)
that fires OutOfBoundException when `bounds.isEmpty() = true`
2. the warning message is populated using the Exception.getMessage

As per point 1, I'm not a DMN expert, and I do not know if the  `bounds.isEmpty() = true` condition could be valid or not; anyway, I have the impression that if it is an invalid situation, it should be returned directly as such, and if it is valid it should not raise any warning.

As per point 2, since the solution should be valid everytime there is an unmanaged situation/exception (IIUC), the only solution that comes to my mind would be to add, in the message, the last "kie" method invoked (looked from stacktrace), but even with that I'm not sure how could be useful.

Any comment/suggestion is appreciated, thanks!

**Comment by tarilabs** [comment]
> The unhelpful message may be just a consequence of some other problem, we may not need a new error message for this

this ☝️

**Comment by gitgabrio** [comment]
@tarilabs @baldimir

So, wha't the expected behavior when

`bounds.isEmpty() = true` ?

[Here](https://github.com/kiegroup/drools/blob/ca1a166c609cc7b3e2867b7968a92adeff80d630/kie-dmn/kie-dmn-validation/src/main/java/org/kie/dmn/validation/dtanalysis/DMNDTAnalyser.java#L515) it is managed in a slightly different way

**Comment by baldimir** [comment]
It needed investigation from my side, so I fixed it directly. Please see https://github.com/kiegroup/drools/pull/4921
