### ISSUE TITLE
flaky tests on `kogito-runtimes`

### ISSUE THREAD

**Issue by eduardocerqueira** [apache/incubator-kie-issues#806]
There are some tests failing on `kogito-runtimes` CI Nightly (branch quarkus3) that need to be investigated and stabilized in preparation for the release.

Tests:
https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/nightly.native/job/kogito-runtimes.build-and-test/96/#showFailuresLink

**Comment by pefernan** [comment]
Looks like the error happens when the `PythonWorkItemHandlers` try initialize the python interpreter (https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/kogito-serverless-workflow/kogito-serverless-workflow-python-runtime/src/main/java/org/kie/kogito/serverless/workflow/python/PythonWorkItemHandlerUtils.java#L41). Somehow the the app cannot run the native python `init` ending up with a NPE that we see in the logs

The same test works fine with the java runner.

**Comment by pefernan** [comment]
Rised https://github.com/apache/incubator-kie-issues/issues/818 to handle a proper fix for python suport in native images. Temporally let's disable again the IT tests (https://github.com/apache/incubator-kie-kogito-runtimes/pull/3347)
