### ISSUE TITLE
Make Optaplanner build reproducible

### ISSUE THREAD

**Issue by lucamolteni** [apache/incubator-kie-issues#846]
See https://github.com/apache/incubator-kie-issues/issues/820, but for Optaplanner

**Comment by yurloc** [comment]
Blocked by
- ~https://github.com/mojohaus/jaxb2-maven-plugin/issues/296~
- https://github.com/quarkusio/quarkus/issues/38364

**Comment by hboutemy** [comment]
@yurloc did you find any issue with jaxb2 output?

**Comment by yurloc** [comment]
> @yurloc did you find any issue with jaxb2 output?

I didn't. Our manual reproducibility check according to this [guide](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) fails in the `mvn artifact:check-buildplan` step. But when I skip that and just run
```
mvn clean install 
mvn clean verify artifact:compare
```
no difference is detected in modules that use the jaxb2 plugin (we use the `schemagen` goal).

If I understand the situation correctly, in our case `jaxb2-maven-plugin:3.1.0:schemagen` does not make the build non-reproducible.

**Comment by yurloc** [comment]
@hboutemy I've just read your [comment in 296](https://github.com/mojohaus/jaxb2-maven-plugin/issues/296#issuecomment-1907439163) and I agree that we don't have an issue with the jaxb2 plugin, other than failing the `check-buildplan` step. In case this is an optional check, then we're OK. It's just a bit misleading to someone who's new to the reproducible builds because it's not clear how important `check-buildplan` is.

**Comment by hboutemy** [comment]
> other than failing the `check-buildplan` step. In case this is an optional check

yes, `artifact:check-buildplan` is just a helper tool to ease discovering and fixing easy/basic issues: if you see how to improve the wording on https://maven.apache.org/guides/mini/guide-reproducible-builds.html (or anywhere else), please help

FYI, I dropped jaxb2-maven-plugin because it's not really helping currently but more creating complexity

**Comment by lucamolteni** [comment]
> please help

Check this please 

https://github.com/apache/maven-site/pull/489

**Comment by yurloc** [comment]
Second part of the Quarkus timestamps issue:
- https://github.com/quarkusio/quarkus/issues/38420

When we upgrade to a Quarkus version that contains both fixes, we no longer need a workaround.

**Comment by lucamolteni** [comment]
Fixed in https://github.com/apache/incubator-kie-optaplanner/commit/08419e4f7c306ffb80ca17304bc97f21d87f6761
