### ISSUE TITLE
An overhaul of how we handle extensions both in KIE Sandbox and Serverless Logic Web Tools

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#91]
Steps to reproduce:
- Import this URL on KIE Sandbox https://gist.github.com/tiagobento/6cd55debe616913f986dc9e661a68b07#file-test-bpmn-bpmn
- Observe that it opens as a BPMN, but the File Label is not shown (????)
- File name seems correct, but on the URL we see `test.bpmn.bpmn`, so we should see `test.bpmn` at the file name on the Editor Page.
 
> NOTE: There's important information and comments at the original Jira too. See https://issues.redhat.com/browse/KOGITO-4708

Expected behaviour:
- The UI should be able to display the File Label correctly and the name displayed on screen should be `test.bpmn`, as the original file name is `test.bpmn.bpmn`.

**Comment by kbowers-ibm** [comment]
Upon investigation it turns out that this issue has nothing to do with Gist, but rather with how we handle dots in kie-tools. The current behavior is to treat everything after a dot as the file extension, and remove it from the filename. Therefore the scope of this ticket has changed to become an overhaul of how we handle dots in a file. Dots will now be allowed in a file, e.g. the file in the example test.bpmn.bpmn will now show the name test.bpmn with extension .bpmn. It will also support files with multi-dotted extensions in the case of serverless web tools, e.g. sw.json files.
